# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: secret

development:
  <<: *default
  database: weather_statistics_development

test:
  <<: *default
  database: weather_statistics_test

production:
  <<: *default
  database: weather_statistics_production
  username: weather_statistics
  password: <%= ENV["WEATHER_STATISTICS_DATABASE_PASSWORD"] %>
